
name: PGK CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main, test ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['5.0']

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Start MongoDb
      uses: supercharge/mongodb-github-action@1.2.0
      with: 
        mongodb--version: ${{ matrix.node-version }}
        
    - run: npm i
    - run: npm test
